; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "Entry CFG 016e", ROM0[$016e]

Block_016e::
    cp $11
    jr z $0175

SECTION "Entry CFG 0172", ROM0[$0172]

Block_0172::
    xor a
    jr $0177

SECTION "Entry CFG 0175", ROM0[$0175]

Block_0175::
    ld a, $01
    ldh [$ff00 + $e6], a
    ld a, $01
    ldh [$ff00 + $ea], a
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $56], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ld [$d000], a
    ld a, $04
    ldh [$ff00 + $07], a
    ldh a, [$ff00 + $44]
    cp $91
    jr nz $01a2
