; Generated by tools/disassemble_gb_basic_block.py; do not edit by hand.
SECTION "Startup CGB Block", ROM0[$0175]

StartupCgbPath::
    ld a, $01
    ldh [$ff00 + $e6], a
    ld a, $01
    ldh [$ff00 + $ea], a
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $56], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ld [$d000], a
    ld a, $04
    ldh [$ff00 + $07], a
    ldh a, [$ff00 + $44]
    cp $91
    jr nz $01a2
