; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "IT Startup CFG 016e", ROM0[$016e]

Block_016e::
    cp $11
    jr z $0175

SECTION "IT Startup CFG 0172", ROM0[$0172]

Block_0172::
    xor a
    jr $0177

SECTION "IT Startup CFG 0175", ROM0[$0175]

Block_0175::
    ld a, $01

SECTION "IT Startup CFG 0177", ROM0[$0177]

Block_0177::
    ldh [$ff00 + $e6], a
    ld a, $01
    ldh [$ff00 + $ea], a
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $56], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ld [$d000], a
    ld a, $04
    ldh [$ff00 + $07], a
    ldh a, [$ff00 + $44]
    cp $91
    jr nz $01a2

SECTION "IT Startup CFG 01a8", ROM0[$01a8]

Block_01a8::
    xor a
    ldh [$ff00 + $40], a
    ld hl, $c000
    ld bc, $1000
    ld [hl], $00
    inc hl
    dec bc
    ld a, b
    or c
    jr nz $01b1
